const words={pt:{navFlow:'Como funciona',navCommunity:'Comunidade VIP',navEcosystem:'Ecossistema',navConcept:'Conceito',downloadHeader:'Baixar para Windows',downloadItem:'Baixar',home:'Início',downloadSelected:'Baixar selecionados',plugins:'Plugins',methods:'Métodos',selected:'selecionados',plugin:'PLUGIN',method:'MÉTODO',empty:'Nenhum item disponível.'},en:{navFlow:'How it works',navCommunity:'VIP Community',navEcosystem:'Ecosystem',navConcept:'Concept',downloadHeader:'Download for Windows',downloadItem:'Download',home:'Home',downloadSelected:'Download selected',plugins:'Plugins',methods:'Methods',selected:'selected',plugin:'PLUGIN',method:'METHOD',empty:'No items available.'},es:{navFlow:'Cómo funciona',navCommunity:'Comunidad VIP',navEcosystem:'Ecosistema',navConcept:'Concepto',downloadHeader:'Descargar para Windows',downloadItem:'Descargar',home:'Inicio',downloadSelected:'Descargar seleccionados',plugins:'Plugins',methods:'Métodos',selected:'seleccionados',plugin:'PLUGIN',method:'MÉTODO',empty:'No hay elementos disponibles.'}};
const methodData=[['theme','Método de Tema','4 blocos: categoria, ângulo, geração e escolha final.'],['title','Método de Título','2 blocos: opções de título e validação humana.'],['thumbnail','Método de Thumbnail','3 blocos: prompt, geração no Flow e aprovação.'],['script','Método de Roteiro','11 blocos: pesquisa, estrutura, dossiê, roteiro e validação.'],['narration','Método de Narração e Áudio','Geração da narração a partir do roteiro aprovado.'],['assets','Método de Assets Visuais','SRT, prompts visuais e imagens em lote no Flow.']].map(([slug,name,description])=>({slug,name,description,url:`downloads/methods/historicos-contentflow-${slug}.contentflow-method.zip`}));
let language=localStorage.getItem('contentflow-site-language')||'pt',kind='plugins',catalog=[],selected=new Set();const g=document.querySelector('#gallery'),count=document.querySelector('#selection-count'),download=document.querySelector('#download-selected');
function icon(plugin){return `ecosystem-assets/plugin-${plugin.downloadUrl.replace('ContentFlow-Plugin-','').replace('.zip','')}.png`}
function urlFor(item){return kind==='plugins'?`https://github.com/andremjr/contentflow/releases/latest/download/${item.downloadUrl}`:item.url}
function render(){const data=kind==='plugins'?catalog:methodData;g.innerHTML=data.length?data.map(item=>{const url=urlFor(item);return `<article class="card ${kind==='plugins'?'plugin':''}"><label><input class="select" type="checkbox" data-url="${url}" ${selected.has(url)?'checked':''}></label><div class="cover"><img src="${kind==='plugins'?icon(item):'ecosystem-assets/historicos.webp'}" onerror="this.src='logo-mark.png'" alt="${item.name}"></div><div class="body"><small>${words[language][kind==='plugins'?'plugin':'method']}</small><h2>${item.name}</h2><p>${item.description}</p><a href="${url}" download>${words[language].downloadItem}</a></div></article>`}).join(''):`<div class="empty">${words[language].empty}</div>`;g.querySelectorAll('.select').forEach(box=>box.onchange=()=>{box.checked?selected.add(box.dataset.url):selected.delete(box.dataset.url);update()});update()}
function update(){count.textContent=selected.size?`${selected.size} ${words[language].selected}`:'';download.disabled=!selected.size}
function setLanguage(nextLanguage){language=nextLanguage;document.documentElement.lang=language==='pt'?'pt-BR':language;document.querySelectorAll('[data-i18n]').forEach(element=>element.textContent=words[language][element.dataset.i18n]);document.querySelectorAll('[data-language]').forEach(element=>element.setAttribute('aria-pressed',element.dataset.language===language));localStorage.setItem('contentflow-site-language',language);render()}
document.querySelectorAll('[data-language]').forEach(element=>element.onclick=()=>setLanguage(element.dataset.language));document.querySelectorAll('.tab').forEach(element=>element.onclick=()=>{kind=element.dataset.kind;selected.clear();document.querySelectorAll('.tab').forEach(tab=>tab.classList.toggle('active',tab===element));render()});download.onclick=()=>[...selected].forEach((url,index)=>setTimeout(()=>{const link=document.createElement('a');link.href=url;link.download='';link.click()},index*400));fetch(new URL('ecosystem-catalog.json',document.baseURI)).then(response=>response.json()).then(data=>{catalog=data.plugins.map((plugin,index)=>({...plugin,slug:`plugin-${index}`}));setLanguage(language)}).catch(()=>setLanguage(language));
