const t = {
  pt: [
    "Como funciona",
    "Conceito",
    "Baixar para Windows",
    "Grátis · Instalador oficial",
    "CONTENTFLOW PARA WINDOWS",
    "Seu processo de conteúdo.<br><em>Do seu jeito.</em>",
    "Organize cada vídeo, transforme sua estratégia em Métodos e conecte as ferramentas que fazem o trabalho acontecer.",
    "Entenda o conceito →",
    "Windows 10 ou 11 · Sem login obrigatório",
    "SEU ESPAÇO DE TRABALHO",
    "Canal: Tudo sobre vídeos",
    "+ Novo projeto",
    "PROJETOS",
    "EM PRODUÇÃO",
    "MÉTODOS",
    "PRODUZINDO AGORA",
    "O vídeo que muda sua estratégia",
    "A estratégia é sua.",
    "As ferramentas podem mudar.",
    "O Método continua.",
    "COMECE EM MINUTOS",
    "Cinco passos. Um fluxo claro.",
    "Do primeiro download ao primeiro vídeo em produção.",
    "Instale",
    "Baixe o instalador oficial e abra o ContentFlow no Windows.",
    "Crie seu canal",
    "Dê um espaço próprio para sua estratégia, projetos e referências.",
    "Crie ou importe Métodos",
    "Organize o passo a passo que transforma uma ideia em vídeo.",
    "Conecte plugins",
    "Escolha quem executa cada etapa: você, IA, código ou uma ferramenta.",
    "Comece a produzir",
    "Acompanhe cada projeto e avance quando estiver pronto.",
    "SEU JEITO DE PRODUZIR",
    "Método não é uma lista solta de prompts.",
    "É o mapa do seu processo: o que vem primeiro, quem faz cada parte, o que entra e o que precisa sair.",
    "Conheça os Métodos →",
    "PROCESSO 04 · ROTEIRO",
    "Pronto para executar",
    "Buscar referências",
    "Escolher estrutura",
    "Criar roteiro",
    "O Método guarda a estratégia. Plugins executam cada etapa.",
    "COMUNIDADE CONTENTFLOW VIP",
    "Não aprenda sozinho<br>a produzir melhor.",
    "Participe de três aulas ao vivo por semana para tirar dúvidas sobre o aplicativo, acompanhar as melhorias em tempo real e aprender estratégia de YouTube com o ContentFlow como base.",
    "3 AULAS AO VIVO / SEMANA",
    "Tire dúvidas diretamente sobre o aplicativo",
    "Participe das melhorias em tempo real",
    "Aprenda estratégia de YouTube na prática",
    "Quero participar da comunidade →",
    "As inscrições serão divulgadas em breve.",
    "Seu Método. Seu canal.<br>Seu próximo vídeo.",
  ],
  en: [
    "How it works",
    "Concept",
    "Download for Windows",
    "Free · Official installer",
    "CONTENTFLOW FOR WINDOWS",
    "Your content process.<br><em>Your way.</em>",
    "Organize every video, turn your strategy into Methods, and connect the tools that make the work happen.",
    "Understand the concept →",
    "Windows 10 or 11 · No sign-in required",
    "YOUR WORKSPACE",
    "Channel: All about videos",
    "+ New project",
    "PROJECTS",
    "IN PRODUCTION",
    "METHODS",
    "PRODUCING NOW",
    "The video that changes your strategy",
    "The strategy is yours.",
    "Tools can change.",
    "The Method remains.",
    "START IN MINUTES",
    "Five steps. One clear flow.",
    "From the first download to your first video in production.",
    "Install",
    "Download the official installer and open ContentFlow on Windows.",
    "Create your channel",
    "Give your strategy, projects, and references a space of their own.",
    "Create or import Methods",
    "Organize the steps that turn an idea into a video.",
    "Connect plugins",
    "Choose who executes every step: you, AI, code, or a tool.",
    "Start producing",
    "Follow each project and move ahead when it is ready.",
    "YOUR WAY OF PRODUCING",
    "A Method is not a loose list of prompts.",
    "It is the map of your process: what comes first, who does each part, what goes in, and what must come out.",
    "Explore Methods →",
    "PROCESS 04 · SCRIPT",
    "Ready to run",
    "Find references",
    "Choose structure",
    "Create script",
    "The Method keeps the strategy. Plugins run every step.",
    "CONTENTFLOW VIP COMMUNITY",
    "Do not learn to<br>produce better alone.",
    "Join three live classes each week to ask questions about the app, follow improvements in real time, and learn YouTube strategy with ContentFlow as your foundation.",
    "3 LIVE CLASSES / WEEK",
    "Ask questions directly about the app",
    "Take part in improvements in real time",
    "Learn hands-on YouTube strategy",
    "I want to join the community →",
    "Enrollment details will be announced soon.",
    "Your Method. Your channel.<br>Your next video.",
  ],
  es: [
    "Cómo funciona",
    "Concepto",
    "Descargar para Windows",
    "Gratis · Instalador oficial",
    "CONTENTFLOW PARA WINDOWS",
    "Tu proceso de contenido.<br><em>A tu manera.</em>",
    "Organiza cada vídeo, transforma tu estrategia en Métodos y conecta las herramientas que hacen que el trabajo suceda.",
    "Entiende el concepto →",
    "Windows 10 u 11 · Sin inicio de sesión obligatorio",
    "TU ESPACIO DE TRABAJO",
    "Canal: Todo sobre vídeos",
    "+ Nuevo proyecto",
    "PROYECTOS",
    "EN PRODUCCIÓN",
    "MÉTODOS",
    "PRODUCIENDO AHORA",
    "El vídeo que cambia tu estrategia",
    "La estrategia es tuya.",
    "Las herramientas pueden cambiar.",
    "El Método continúa.",
    "EMPIEZA EN MINUTOS",
    "Cinco pasos. Un flujo claro.",
    "Desde la primera descarga hasta tu primer vídeo en producción.",
    "Instala",
    "Descarga el instalador oficial y abre ContentFlow en Windows.",
    "Crea tu canal",
    "Da un espacio propio a tu estrategia, proyectos y referencias.",
    "Crea o importa Métodos",
    "Organiza el paso a paso que transforma una idea en vídeo.",
    "Conecta plugins",
    "Elige quién ejecuta cada etapa: tú, IA, código o una herramienta.",
    "Empieza a producir",
    "Sigue cada proyecto y avanza cuando esté listo.",
    "TU FORMA DE PRODUCIR",
    "Un Método no es una lista suelta de prompts.",
    "Es el mapa de tu proceso: qué viene primero, quién hace cada parte, qué entra y qué debe salir.",
    "Conoce los Métodos →",
    "PROCESO 04 · GUIÓN",
    "Listo para ejecutar",
    "Buscar referencias",
    "Elegir estructura",
    "Crear guión",
    "El Método guarda la estrategia. Los plugins ejecutan cada etapa.",
    "COMUNIDAD CONTENTFLOW VIP",
    "No aprendas a producir<br>mejor por tu cuenta.",
    "Participa en tres clases en vivo por semana para resolver dudas sobre la aplicación, seguir las mejoras en tiempo real y aprender estrategia de YouTube con ContentFlow como base.",
    "3 CLASES EN VIVO / SEMANA",
    "Resuelve dudas directamente sobre la aplicación",
    "Participa en mejoras en tiempo real",
    "Aprende estrategia de YouTube en la práctica",
    "Quiero participar en la comunidad →",
    "Las inscripciones se anunciarán pronto.",
    "Tu Método. Tu canal.<br>Tu próximo vídeo.",
  ],
};
const k = [
  "navFlow",
  "navConcept",
  "download",
  "downloadNote",
  "eyebrow",
  "heroTitle",
  "heroText",
  "learnMore",
  "system",
  "previewLabel",
  "previewTitle",
  "newProject",
  "projects",
  "inProgress",
  "methods",
  "nowProducing",
  "projectTitle",
  "trustOne",
  "trustTwo",
  "trustThree",
  "flowEyebrow",
  "flowTitle",
  "flowText",
  "step1Title",
  "step1Text",
  "step2Title",
  "step2Text",
  "step3Title",
  "step3Text",
  "step4Title",
  "step4Text",
  "step5Title",
  "step5Text",
  "methodEyebrow",
  "methodTitle",
  "methodText",
  "methodLink",
  "boardProcess",
  "boardReady",
  "boardOne",
  "boardTwo",
  "boardThree",
  "boardFooter",
  "vipEyebrow",
  "vipTitle",
  "vipText",
  "vipLive",
  "vipOne",
  "vipTwo",
  "vipThree",
  "vipButton",
  "vipNote",
  "finalTitle",
];
function setLanguage(l) {
  document.documentElement.lang = l === "pt" ? "pt-BR" : l;
  document
    .querySelectorAll("[data-i18n]")
    .forEach((n) => (n.innerHTML = t[l][k.indexOf(n.dataset.i18n)]));
  document
    .querySelectorAll("[data-language]")
    .forEach((b) => b.setAttribute("aria-pressed", b.dataset.language === l));
  localStorage.setItem("contentflow-site-language", l);
}
document
  .querySelectorAll("[data-language]")
  .forEach((b) => (b.onclick = () => setLanguage(b.dataset.language)));
setLanguage(localStorage.getItem("contentflow-site-language") || "pt");
const extraLabels = { pt: { navCommunity: "Comunidade VIP", navEcosystem: "Ecossistema", freeForever: "ContentFlow é gratuito. E sempre será." }, en: { navCommunity: "VIP Community", navEcosystem: "Ecosystem", freeForever: "ContentFlow is free. And always will be." }, es: { navCommunity: "Comunidad VIP", navEcosystem: "Ecosistema", freeForever: "ContentFlow es gratuito. Y siempre lo será." } };
function setExtraLabels() { const language = localStorage.getItem("contentflow-site-language") || "pt"; document.querySelectorAll('[data-i18n="navCommunity"], [data-i18n="navEcosystem"], [data-i18n="freeForever"]').forEach((node) => node.innerHTML = extraLabels[language][node.dataset.i18n]); }
setExtraLabels();
document.querySelectorAll("[data-language]").forEach((button) => button.addEventListener("click", setExtraLabels));
