import { checkRegistry } from "./checks";
import { scenarios } from "./scenarios";

export const coverageMatrix = [
  ...checkRegistry.map((check) => ({
    rule: check.id,
    reference: check.reference,
    classification: "IMPLEMENTED",
    events: `${check.domain}:${check.entityType}`,
    projector: "entity lifecycle",
    check: check.id,
    scenarios: Object.values(scenarios)
      .filter((s) => s.requiredChecks?.includes(check.id))
      .map((s) => s.name),
    coverageGap: !Object.values(scenarios).some((s) => s.requiredChecks?.includes(check.id)),
  })),
  {
    rule: "External effect replay forbidden until reconciliation",
    reference: "docs/reliability-program/decisions/ADR-004-UNCERTAIN-EXTERNAL-EFFECTS.md",
    classification: "PARTIALLY_IMPLEMENTABLE",
    events: "command outcome unknown; receipt hash",
    projector: "command/attempt",
    check: null,
    scenarios: ["sandbox-faults"],
    coverageGap: true,
  },
  {
    rule: "Plugin work item IDs granted before effect",
    reference: "docs/reliability-program/01-TARGET-ARCHITECTURE.md#9",
    classification: "DEFERRED",
    events: "item commit + delegated effect causal link",
    check: null,
    scenarios: [],
    coverageGap: true,
  },
  {
    rule: "Bindings and readiness explicit",
    reference: "docs/ARCHITECTURE.md#6",
    classification: "PARTIALLY_IMPLEMENTABLE",
    events: "binding commit/readiness before invocation",
    check: null,
    scenarios: [],
    coverageGap: true,
  },
  {
    rule: "Method semantic intent and editorial quality",
    reference: "docs/reliability-program/00-PRODUCT-CONSTITUTION.md#1",
    classification: "NOT_MACHINE_CHECKABLE",
    check: null,
    scenarios: [],
    coverageGap: false,
  },
  {
    rule: "Frozen strategy preserved across restart",
    reference: "docs/reliability-program/00-PRODUCT-CONSTITUTION.md#3",
    classification: "DEFERRED",
    events: "snapshot hash before/after restart",
    check: null,
    scenarios: [],
    coverageGap: true,
  },
  {
    rule: "Atomic durable commit and UI agrees",
    reference: "docs/reliability-program/01-TARGET-ARCHITECTURE.md#6",
    classification: "PARTIALLY_IMPLEMENTABLE",
    events: "postcommit snapshots + renderer projection",
    check: null,
    scenarios: ["human-theme"],
    coverageGap: true,
  },
  {
    rule: "Independent queues continue / five videos",
    reference: "docs/reliability-program/00-PRODUCT-CONSTITUTION.md#6",
    classification: "DEFERRED",
    events: "scheduler eligibility + queue transitions",
    check: null,
    scenarios: [],
    coverageGap: true,
  },
  {
    rule: "Hardware resource bounds / backpressure",
    reference: "docs/reliability-program/decisions/ADR-006-RESOURCE-CONSERVATIVE-EXECUTION.md",
    classification: "PARTIALLY_IMPLEMENTABLE",
    events: "resource measurements",
    check: null,
    scenarios: [],
    coverageGap: true,
  },
  {
    rule: "Recoverable historical storage migrations",
    reference: "docs/reliability-program/01-TARGET-ARCHITECTURE.md#8",
    classification: "DEFERRED",
    events: "migration plan + backup + recovery proof",
    check: null,
    scenarios: [],
    coverageGap: true,
  },
  {
    rule: "Deterministic input/output material contracts",
    reference: "docs/CONTENT_CONTRACT.md",
    classification: "PARTIALLY_IMPLEMENTABLE",
    events: "required output count",
    check: "CORE.BLOCK.REQUIRED_OUTPUTS",
    scenarios: ["human-theme"],
    coverageGap: true,
  },
  {
    rule: "Bounded recovery decisions preserve completed work",
    reference: "docs/reliability-program/01-TARGET-ARCHITECTURE.md#11",
    classification: "DEFERRED",
    events: "recovery decision + revision/history",
    check: null,
    scenarios: [],
    coverageGap: true,
  },
];
