/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectProjectIdRouteImport } from './routes/project.$projectId'
import { Route as ChannelChannelIdRouteImport } from './routes/channel.$channelId'
import { Route as ProjectProjectIdTitlesRouteImport } from './routes/project.$projectId.titles'
import { Route as ProjectProjectIdThumbnailRouteImport } from './routes/project.$projectId.thumbnail'
import { Route as ProjectProjectIdResearchRouteImport } from './routes/project.$projectId.research'
import { Route as ProjectProjectIdIdeasRouteImport } from './routes/project.$projectId.ideas'
import { Route as ChannelChannelIdTitlesRouteImport } from './routes/channel.$channelId.titles'
import { Route as ChannelChannelIdThumbnailRouteImport } from './routes/channel.$channelId.thumbnail'
import { Route as ChannelChannelIdScriptRouteImport } from './routes/channel.$channelId.script'
import { Route as ChannelChannelIdResearchRouteImport } from './routes/channel.$channelId.research'
import { Route as ChannelChannelIdPublishRouteImport } from './routes/channel.$channelId.publish'
import { Route as ChannelChannelIdNarrationRouteImport } from './routes/channel.$channelId.narration'
import { Route as ChannelChannelIdIdeasRouteImport } from './routes/channel.$channelId.ideas'
import { Route as ChannelChannelIdEditRouteImport } from './routes/channel.$channelId.edit'
import { Route as ChannelChannelIdAssetsRouteImport } from './routes/channel.$channelId.assets'
import { Route as ChannelChannelIdSettingsProcessesRouteImport } from './routes/channel.$channelId.settings.processes'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdRoute = ProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelChannelIdRoute = ChannelChannelIdRouteImport.update({
  id: '/channel/$channelId',
  path: '/channel/$channelId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdTitlesRoute = ProjectProjectIdTitlesRouteImport.update({
  id: '/titles',
  path: '/titles',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ProjectProjectIdThumbnailRoute =
  ProjectProjectIdThumbnailRouteImport.update({
    id: '/thumbnail',
    path: '/thumbnail',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)
const ProjectProjectIdResearchRoute =
  ProjectProjectIdResearchRouteImport.update({
    id: '/research',
    path: '/research',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)
const ProjectProjectIdIdeasRoute = ProjectProjectIdIdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ChannelChannelIdTitlesRoute = ChannelChannelIdTitlesRouteImport.update({
  id: '/titles',
  path: '/titles',
  getParentRoute: () => ChannelChannelIdRoute,
} as any)
const ChannelChannelIdThumbnailRoute =
  ChannelChannelIdThumbnailRouteImport.update({
    id: '/thumbnail',
    path: '/thumbnail',
    getParentRoute: () => ChannelChannelIdRoute,
  } as any)
const ChannelChannelIdScriptRoute = ChannelChannelIdScriptRouteImport.update({
  id: '/script',
  path: '/script',
  getParentRoute: () => ChannelChannelIdRoute,
} as any)
const ChannelChannelIdResearchRoute =
  ChannelChannelIdResearchRouteImport.update({
    id: '/research',
    path: '/research',
    getParentRoute: () => ChannelChannelIdRoute,
  } as any)
const ChannelChannelIdPublishRoute = ChannelChannelIdPublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => ChannelChannelIdRoute,
} as any)
const ChannelChannelIdNarrationRoute =
  ChannelChannelIdNarrationRouteImport.update({
    id: '/narration',
    path: '/narration',
    getParentRoute: () => ChannelChannelIdRoute,
  } as any)
const ChannelChannelIdIdeasRoute = ChannelChannelIdIdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => ChannelChannelIdRoute,
} as any)
const ChannelChannelIdEditRoute = ChannelChannelIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ChannelChannelIdRoute,
} as any)
const ChannelChannelIdAssetsRoute = ChannelChannelIdAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => ChannelChannelIdRoute,
} as any)
const ChannelChannelIdSettingsProcessesRoute =
  ChannelChannelIdSettingsProcessesRouteImport.update({
    id: '/settings/processes',
    path: '/settings/processes',
    getParentRoute: () => ChannelChannelIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/channel/$channelId': typeof ChannelChannelIdRouteWithChildren
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/channel/$channelId/assets': typeof ChannelChannelIdAssetsRoute
  '/channel/$channelId/edit': typeof ChannelChannelIdEditRoute
  '/channel/$channelId/ideas': typeof ChannelChannelIdIdeasRoute
  '/channel/$channelId/narration': typeof ChannelChannelIdNarrationRoute
  '/channel/$channelId/publish': typeof ChannelChannelIdPublishRoute
  '/channel/$channelId/research': typeof ChannelChannelIdResearchRoute
  '/channel/$channelId/script': typeof ChannelChannelIdScriptRoute
  '/channel/$channelId/thumbnail': typeof ChannelChannelIdThumbnailRoute
  '/channel/$channelId/titles': typeof ChannelChannelIdTitlesRoute
  '/project/$projectId/ideas': typeof ProjectProjectIdIdeasRoute
  '/project/$projectId/research': typeof ProjectProjectIdResearchRoute
  '/project/$projectId/thumbnail': typeof ProjectProjectIdThumbnailRoute
  '/project/$projectId/titles': typeof ProjectProjectIdTitlesRoute
  '/channel/$channelId/settings/processes': typeof ChannelChannelIdSettingsProcessesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/channel/$channelId': typeof ChannelChannelIdRouteWithChildren
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/channel/$channelId/assets': typeof ChannelChannelIdAssetsRoute
  '/channel/$channelId/edit': typeof ChannelChannelIdEditRoute
  '/channel/$channelId/ideas': typeof ChannelChannelIdIdeasRoute
  '/channel/$channelId/narration': typeof ChannelChannelIdNarrationRoute
  '/channel/$channelId/publish': typeof ChannelChannelIdPublishRoute
  '/channel/$channelId/research': typeof ChannelChannelIdResearchRoute
  '/channel/$channelId/script': typeof ChannelChannelIdScriptRoute
  '/channel/$channelId/thumbnail': typeof ChannelChannelIdThumbnailRoute
  '/channel/$channelId/titles': typeof ChannelChannelIdTitlesRoute
  '/project/$projectId/ideas': typeof ProjectProjectIdIdeasRoute
  '/project/$projectId/research': typeof ProjectProjectIdResearchRoute
  '/project/$projectId/thumbnail': typeof ProjectProjectIdThumbnailRoute
  '/project/$projectId/titles': typeof ProjectProjectIdTitlesRoute
  '/channel/$channelId/settings/processes': typeof ChannelChannelIdSettingsProcessesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/channel/$channelId': typeof ChannelChannelIdRouteWithChildren
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/channel/$channelId/assets': typeof ChannelChannelIdAssetsRoute
  '/channel/$channelId/edit': typeof ChannelChannelIdEditRoute
  '/channel/$channelId/ideas': typeof ChannelChannelIdIdeasRoute
  '/channel/$channelId/narration': typeof ChannelChannelIdNarrationRoute
  '/channel/$channelId/publish': typeof ChannelChannelIdPublishRoute
  '/channel/$channelId/research': typeof ChannelChannelIdResearchRoute
  '/channel/$channelId/script': typeof ChannelChannelIdScriptRoute
  '/channel/$channelId/thumbnail': typeof ChannelChannelIdThumbnailRoute
  '/channel/$channelId/titles': typeof ChannelChannelIdTitlesRoute
  '/project/$projectId/ideas': typeof ProjectProjectIdIdeasRoute
  '/project/$projectId/research': typeof ProjectProjectIdResearchRoute
  '/project/$projectId/thumbnail': typeof ProjectProjectIdThumbnailRoute
  '/project/$projectId/titles': typeof ProjectProjectIdTitlesRoute
  '/channel/$channelId/settings/processes': typeof ChannelChannelIdSettingsProcessesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/channel/$channelId'
    | '/project/$projectId'
    | '/channel/$channelId/assets'
    | '/channel/$channelId/edit'
    | '/channel/$channelId/ideas'
    | '/channel/$channelId/narration'
    | '/channel/$channelId/publish'
    | '/channel/$channelId/research'
    | '/channel/$channelId/script'
    | '/channel/$channelId/thumbnail'
    | '/channel/$channelId/titles'
    | '/project/$projectId/ideas'
    | '/project/$projectId/research'
    | '/project/$projectId/thumbnail'
    | '/project/$projectId/titles'
    | '/channel/$channelId/settings/processes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/channel/$channelId'
    | '/project/$projectId'
    | '/channel/$channelId/assets'
    | '/channel/$channelId/edit'
    | '/channel/$channelId/ideas'
    | '/channel/$channelId/narration'
    | '/channel/$channelId/publish'
    | '/channel/$channelId/research'
    | '/channel/$channelId/script'
    | '/channel/$channelId/thumbnail'
    | '/channel/$channelId/titles'
    | '/project/$projectId/ideas'
    | '/project/$projectId/research'
    | '/project/$projectId/thumbnail'
    | '/project/$projectId/titles'
    | '/channel/$channelId/settings/processes'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/channel/$channelId'
    | '/project/$projectId'
    | '/channel/$channelId/assets'
    | '/channel/$channelId/edit'
    | '/channel/$channelId/ideas'
    | '/channel/$channelId/narration'
    | '/channel/$channelId/publish'
    | '/channel/$channelId/research'
    | '/channel/$channelId/script'
    | '/channel/$channelId/thumbnail'
    | '/channel/$channelId/titles'
    | '/project/$projectId/ideas'
    | '/project/$projectId/research'
    | '/project/$projectId/thumbnail'
    | '/project/$projectId/titles'
    | '/channel/$channelId/settings/processes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ChannelChannelIdRoute: typeof ChannelChannelIdRouteWithChildren
  ProjectProjectIdRoute: typeof ProjectProjectIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel/$channelId': {
      id: '/channel/$channelId'
      path: '/channel/$channelId'
      fullPath: '/channel/$channelId'
      preLoaderRoute: typeof ChannelChannelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId/titles': {
      id: '/project/$projectId/titles'
      path: '/titles'
      fullPath: '/project/$projectId/titles'
      preLoaderRoute: typeof ProjectProjectIdTitlesRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/thumbnail': {
      id: '/project/$projectId/thumbnail'
      path: '/thumbnail'
      fullPath: '/project/$projectId/thumbnail'
      preLoaderRoute: typeof ProjectProjectIdThumbnailRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/research': {
      id: '/project/$projectId/research'
      path: '/research'
      fullPath: '/project/$projectId/research'
      preLoaderRoute: typeof ProjectProjectIdResearchRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/ideas': {
      id: '/project/$projectId/ideas'
      path: '/ideas'
      fullPath: '/project/$projectId/ideas'
      preLoaderRoute: typeof ProjectProjectIdIdeasRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/channel/$channelId/titles': {
      id: '/channel/$channelId/titles'
      path: '/titles'
      fullPath: '/channel/$channelId/titles'
      preLoaderRoute: typeof ChannelChannelIdTitlesRouteImport
      parentRoute: typeof ChannelChannelIdRoute
    }
    '/channel/$channelId/thumbnail': {
      id: '/channel/$channelId/thumbnail'
      path: '/thumbnail'
      fullPath: '/channel/$channelId/thumbnail'
      preLoaderRoute: typeof ChannelChannelIdThumbnailRouteImport
      parentRoute: typeof ChannelChannelIdRoute
    }
    '/channel/$channelId/script': {
      id: '/channel/$channelId/script'
      path: '/script'
      fullPath: '/channel/$channelId/script'
      preLoaderRoute: typeof ChannelChannelIdScriptRouteImport
      parentRoute: typeof ChannelChannelIdRoute
    }
    '/channel/$channelId/research': {
      id: '/channel/$channelId/research'
      path: '/research'
      fullPath: '/channel/$channelId/research'
      preLoaderRoute: typeof ChannelChannelIdResearchRouteImport
      parentRoute: typeof ChannelChannelIdRoute
    }
    '/channel/$channelId/publish': {
      id: '/channel/$channelId/publish'
      path: '/publish'
      fullPath: '/channel/$channelId/publish'
      preLoaderRoute: typeof ChannelChannelIdPublishRouteImport
      parentRoute: typeof ChannelChannelIdRoute
    }
    '/channel/$channelId/narration': {
      id: '/channel/$channelId/narration'
      path: '/narration'
      fullPath: '/channel/$channelId/narration'
      preLoaderRoute: typeof ChannelChannelIdNarrationRouteImport
      parentRoute: typeof ChannelChannelIdRoute
    }
    '/channel/$channelId/ideas': {
      id: '/channel/$channelId/ideas'
      path: '/ideas'
      fullPath: '/channel/$channelId/ideas'
      preLoaderRoute: typeof ChannelChannelIdIdeasRouteImport
      parentRoute: typeof ChannelChannelIdRoute
    }
    '/channel/$channelId/edit': {
      id: '/channel/$channelId/edit'
      path: '/edit'
      fullPath: '/channel/$channelId/edit'
      preLoaderRoute: typeof ChannelChannelIdEditRouteImport
      parentRoute: typeof ChannelChannelIdRoute
    }
    '/channel/$channelId/assets': {
      id: '/channel/$channelId/assets'
      path: '/assets'
      fullPath: '/channel/$channelId/assets'
      preLoaderRoute: typeof ChannelChannelIdAssetsRouteImport
      parentRoute: typeof ChannelChannelIdRoute
    }
    '/channel/$channelId/settings/processes': {
      id: '/channel/$channelId/settings/processes'
      path: '/settings/processes'
      fullPath: '/channel/$channelId/settings/processes'
      preLoaderRoute: typeof ChannelChannelIdSettingsProcessesRouteImport
      parentRoute: typeof ChannelChannelIdRoute
    }
  }
}

interface ChannelChannelIdRouteChildren {
  ChannelChannelIdAssetsRoute: typeof ChannelChannelIdAssetsRoute
  ChannelChannelIdEditRoute: typeof ChannelChannelIdEditRoute
  ChannelChannelIdIdeasRoute: typeof ChannelChannelIdIdeasRoute
  ChannelChannelIdNarrationRoute: typeof ChannelChannelIdNarrationRoute
  ChannelChannelIdPublishRoute: typeof ChannelChannelIdPublishRoute
  ChannelChannelIdResearchRoute: typeof ChannelChannelIdResearchRoute
  ChannelChannelIdScriptRoute: typeof ChannelChannelIdScriptRoute
  ChannelChannelIdThumbnailRoute: typeof ChannelChannelIdThumbnailRoute
  ChannelChannelIdTitlesRoute: typeof ChannelChannelIdTitlesRoute
  ChannelChannelIdSettingsProcessesRoute: typeof ChannelChannelIdSettingsProcessesRoute
}

const ChannelChannelIdRouteChildren: ChannelChannelIdRouteChildren = {
  ChannelChannelIdAssetsRoute: ChannelChannelIdAssetsRoute,
  ChannelChannelIdEditRoute: ChannelChannelIdEditRoute,
  ChannelChannelIdIdeasRoute: ChannelChannelIdIdeasRoute,
  ChannelChannelIdNarrationRoute: ChannelChannelIdNarrationRoute,
  ChannelChannelIdPublishRoute: ChannelChannelIdPublishRoute,
  ChannelChannelIdResearchRoute: ChannelChannelIdResearchRoute,
  ChannelChannelIdScriptRoute: ChannelChannelIdScriptRoute,
  ChannelChannelIdThumbnailRoute: ChannelChannelIdThumbnailRoute,
  ChannelChannelIdTitlesRoute: ChannelChannelIdTitlesRoute,
  ChannelChannelIdSettingsProcessesRoute:
    ChannelChannelIdSettingsProcessesRoute,
}

const ChannelChannelIdRouteWithChildren =
  ChannelChannelIdRoute._addFileChildren(ChannelChannelIdRouteChildren)

interface ProjectProjectIdRouteChildren {
  ProjectProjectIdIdeasRoute: typeof ProjectProjectIdIdeasRoute
  ProjectProjectIdResearchRoute: typeof ProjectProjectIdResearchRoute
  ProjectProjectIdThumbnailRoute: typeof ProjectProjectIdThumbnailRoute
  ProjectProjectIdTitlesRoute: typeof ProjectProjectIdTitlesRoute
}

const ProjectProjectIdRouteChildren: ProjectProjectIdRouteChildren = {
  ProjectProjectIdIdeasRoute: ProjectProjectIdIdeasRoute,
  ProjectProjectIdResearchRoute: ProjectProjectIdResearchRoute,
  ProjectProjectIdThumbnailRoute: ProjectProjectIdThumbnailRoute,
  ProjectProjectIdTitlesRoute: ProjectProjectIdTitlesRoute,
}

const ProjectProjectIdRouteWithChildren =
  ProjectProjectIdRoute._addFileChildren(ProjectProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ChannelChannelIdRoute: ChannelChannelIdRouteWithChildren,
  ProjectProjectIdRoute: ProjectProjectIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
