/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChannelChannelIdRouteImport } from './routes/channel.$channelId'
import { Route as ChannelChannelIdTitlesRouteImport } from './routes/channel.$channelId.titles'
import { Route as ChannelChannelIdResearchRouteImport } from './routes/channel.$channelId.research'
import { Route as ChannelChannelIdIdeasRouteImport } from './routes/channel.$channelId.ideas'
import { Route as ChannelChannelIdSettingsProcessesRouteImport } from './routes/channel.$channelId.settings.processes'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelChannelIdRoute = ChannelChannelIdRouteImport.update({
  id: '/channel/$channelId',
  path: '/channel/$channelId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelChannelIdTitlesRoute = ChannelChannelIdTitlesRouteImport.update({
  id: '/titles',
  path: '/titles',
  getParentRoute: () => ChannelChannelIdRoute,
} as any)
const ChannelChannelIdResearchRoute =
  ChannelChannelIdResearchRouteImport.update({
    id: '/research',
    path: '/research',
    getParentRoute: () => ChannelChannelIdRoute,
  } as any)
const ChannelChannelIdIdeasRoute = ChannelChannelIdIdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => ChannelChannelIdRoute,
} as any)
const ChannelChannelIdSettingsProcessesRoute =
  ChannelChannelIdSettingsProcessesRouteImport.update({
    id: '/settings/processes',
    path: '/settings/processes',
    getParentRoute: () => ChannelChannelIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/channel/$channelId': typeof ChannelChannelIdRouteWithChildren
  '/channel/$channelId/ideas': typeof ChannelChannelIdIdeasRoute
  '/channel/$channelId/research': typeof ChannelChannelIdResearchRoute
  '/channel/$channelId/titles': typeof ChannelChannelIdTitlesRoute
  '/channel/$channelId/settings/processes': typeof ChannelChannelIdSettingsProcessesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/channel/$channelId': typeof ChannelChannelIdRouteWithChildren
  '/channel/$channelId/ideas': typeof ChannelChannelIdIdeasRoute
  '/channel/$channelId/research': typeof ChannelChannelIdResearchRoute
  '/channel/$channelId/titles': typeof ChannelChannelIdTitlesRoute
  '/channel/$channelId/settings/processes': typeof ChannelChannelIdSettingsProcessesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/channel/$channelId': typeof ChannelChannelIdRouteWithChildren
  '/channel/$channelId/ideas': typeof ChannelChannelIdIdeasRoute
  '/channel/$channelId/research': typeof ChannelChannelIdResearchRoute
  '/channel/$channelId/titles': typeof ChannelChannelIdTitlesRoute
  '/channel/$channelId/settings/processes': typeof ChannelChannelIdSettingsProcessesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/channel/$channelId'
    | '/channel/$channelId/ideas'
    | '/channel/$channelId/research'
    | '/channel/$channelId/titles'
    | '/channel/$channelId/settings/processes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/channel/$channelId'
    | '/channel/$channelId/ideas'
    | '/channel/$channelId/research'
    | '/channel/$channelId/titles'
    | '/channel/$channelId/settings/processes'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/channel/$channelId'
    | '/channel/$channelId/ideas'
    | '/channel/$channelId/research'
    | '/channel/$channelId/titles'
    | '/channel/$channelId/settings/processes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ChannelChannelIdRoute: typeof ChannelChannelIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel/$channelId': {
      id: '/channel/$channelId'
      path: '/channel/$channelId'
      fullPath: '/channel/$channelId'
      preLoaderRoute: typeof ChannelChannelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel/$channelId/titles': {
      id: '/channel/$channelId/titles'
      path: '/titles'
      fullPath: '/channel/$channelId/titles'
      preLoaderRoute: typeof ChannelChannelIdTitlesRouteImport
      parentRoute: typeof ChannelChannelIdRoute
    }
    '/channel/$channelId/research': {
      id: '/channel/$channelId/research'
      path: '/research'
      fullPath: '/channel/$channelId/research'
      preLoaderRoute: typeof ChannelChannelIdResearchRouteImport
      parentRoute: typeof ChannelChannelIdRoute
    }
    '/channel/$channelId/ideas': {
      id: '/channel/$channelId/ideas'
      path: '/ideas'
      fullPath: '/channel/$channelId/ideas'
      preLoaderRoute: typeof ChannelChannelIdIdeasRouteImport
      parentRoute: typeof ChannelChannelIdRoute
    }
    '/channel/$channelId/settings/processes': {
      id: '/channel/$channelId/settings/processes'
      path: '/settings/processes'
      fullPath: '/channel/$channelId/settings/processes'
      preLoaderRoute: typeof ChannelChannelIdSettingsProcessesRouteImport
      parentRoute: typeof ChannelChannelIdRoute
    }
  }
}

interface ChannelChannelIdRouteChildren {
  ChannelChannelIdIdeasRoute: typeof ChannelChannelIdIdeasRoute
  ChannelChannelIdResearchRoute: typeof ChannelChannelIdResearchRoute
  ChannelChannelIdTitlesRoute: typeof ChannelChannelIdTitlesRoute
  ChannelChannelIdSettingsProcessesRoute: typeof ChannelChannelIdSettingsProcessesRoute
}

const ChannelChannelIdRouteChildren: ChannelChannelIdRouteChildren = {
  ChannelChannelIdIdeasRoute: ChannelChannelIdIdeasRoute,
  ChannelChannelIdResearchRoute: ChannelChannelIdResearchRoute,
  ChannelChannelIdTitlesRoute: ChannelChannelIdTitlesRoute,
  ChannelChannelIdSettingsProcessesRoute:
    ChannelChannelIdSettingsProcessesRoute,
}

const ChannelChannelIdRouteWithChildren =
  ChannelChannelIdRoute._addFileChildren(ChannelChannelIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ChannelChannelIdRoute: ChannelChannelIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
