/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectProjectIdIndexRouteImport } from './routes/project.$projectId.index'
import { Route as ChannelChannelIdIndexRouteImport } from './routes/channel.$channelId.index'
import { Route as ProjectProjectIdTitlesRouteImport } from './routes/project.$projectId.titles'
import { Route as ProjectProjectIdThumbnailRouteImport } from './routes/project.$projectId.thumbnail'
import { Route as ProjectProjectIdScriptRouteImport } from './routes/project.$projectId.script'
import { Route as ProjectProjectIdResearchRouteImport } from './routes/project.$projectId.research'
import { Route as ProjectProjectIdPublishRouteImport } from './routes/project.$projectId.publish'
import { Route as ProjectProjectIdNarrationRouteImport } from './routes/project.$projectId.narration'
import { Route as ProjectProjectIdIdeasRouteImport } from './routes/project.$projectId.ideas'
import { Route as ProjectProjectIdEditRouteImport } from './routes/project.$projectId.edit'
import { Route as ProjectProjectIdAssetsRouteImport } from './routes/project.$projectId.assets'
import { Route as ChannelChannelIdTitlesRouteImport } from './routes/channel.$channelId.titles'
import { Route as ChannelChannelIdThumbnailRouteImport } from './routes/channel.$channelId.thumbnail'
import { Route as ChannelChannelIdScriptRouteImport } from './routes/channel.$channelId.script'
import { Route as ChannelChannelIdResearchRouteImport } from './routes/channel.$channelId.research'
import { Route as ChannelChannelIdPublishRouteImport } from './routes/channel.$channelId.publish'
import { Route as ChannelChannelIdNarrationRouteImport } from './routes/channel.$channelId.narration'
import { Route as ChannelChannelIdIdeasRouteImport } from './routes/channel.$channelId.ideas'
import { Route as ChannelChannelIdEditRouteImport } from './routes/channel.$channelId.edit'
import { Route as ChannelChannelIdAssetsRouteImport } from './routes/channel.$channelId.assets'
import { Route as ChannelChannelIdSettingsProcessesRouteImport } from './routes/channel.$channelId.settings.processes'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdIndexRoute = ProjectProjectIdIndexRouteImport.update({
  id: '/project/$projectId/',
  path: '/project/$projectId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelChannelIdIndexRoute = ChannelChannelIdIndexRouteImport.update({
  id: '/channel/$channelId/',
  path: '/channel/$channelId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdTitlesRoute = ProjectProjectIdTitlesRouteImport.update({
  id: '/project/$projectId/titles',
  path: '/project/$projectId/titles',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdThumbnailRoute =
  ProjectProjectIdThumbnailRouteImport.update({
    id: '/project/$projectId/thumbnail',
    path: '/project/$projectId/thumbnail',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectProjectIdScriptRoute = ProjectProjectIdScriptRouteImport.update({
  id: '/project/$projectId/script',
  path: '/project/$projectId/script',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdResearchRoute =
  ProjectProjectIdResearchRouteImport.update({
    id: '/project/$projectId/research',
    path: '/project/$projectId/research',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectProjectIdPublishRoute = ProjectProjectIdPublishRouteImport.update({
  id: '/project/$projectId/publish',
  path: '/project/$projectId/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdNarrationRoute =
  ProjectProjectIdNarrationRouteImport.update({
    id: '/project/$projectId/narration',
    path: '/project/$projectId/narration',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectProjectIdIdeasRoute = ProjectProjectIdIdeasRouteImport.update({
  id: '/project/$projectId/ideas',
  path: '/project/$projectId/ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdEditRoute = ProjectProjectIdEditRouteImport.update({
  id: '/project/$projectId/edit',
  path: '/project/$projectId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdAssetsRoute = ProjectProjectIdAssetsRouteImport.update({
  id: '/project/$projectId/assets',
  path: '/project/$projectId/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelChannelIdTitlesRoute = ChannelChannelIdTitlesRouteImport.update({
  id: '/channel/$channelId/titles',
  path: '/channel/$channelId/titles',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelChannelIdThumbnailRoute =
  ChannelChannelIdThumbnailRouteImport.update({
    id: '/channel/$channelId/thumbnail',
    path: '/channel/$channelId/thumbnail',
    getParentRoute: () => rootRouteImport,
  } as any)
const ChannelChannelIdScriptRoute = ChannelChannelIdScriptRouteImport.update({
  id: '/channel/$channelId/script',
  path: '/channel/$channelId/script',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelChannelIdResearchRoute =
  ChannelChannelIdResearchRouteImport.update({
    id: '/channel/$channelId/research',
    path: '/channel/$channelId/research',
    getParentRoute: () => rootRouteImport,
  } as any)
const ChannelChannelIdPublishRoute = ChannelChannelIdPublishRouteImport.update({
  id: '/channel/$channelId/publish',
  path: '/channel/$channelId/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelChannelIdNarrationRoute =
  ChannelChannelIdNarrationRouteImport.update({
    id: '/channel/$channelId/narration',
    path: '/channel/$channelId/narration',
    getParentRoute: () => rootRouteImport,
  } as any)
const ChannelChannelIdIdeasRoute = ChannelChannelIdIdeasRouteImport.update({
  id: '/channel/$channelId/ideas',
  path: '/channel/$channelId/ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelChannelIdEditRoute = ChannelChannelIdEditRouteImport.update({
  id: '/channel/$channelId/edit',
  path: '/channel/$channelId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelChannelIdAssetsRoute = ChannelChannelIdAssetsRouteImport.update({
  id: '/channel/$channelId/assets',
  path: '/channel/$channelId/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelChannelIdSettingsProcessesRoute =
  ChannelChannelIdSettingsProcessesRouteImport.update({
    id: '/channel/$channelId/settings/processes',
    path: '/channel/$channelId/settings/processes',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/channel/$channelId/assets': typeof ChannelChannelIdAssetsRoute
  '/channel/$channelId/edit': typeof ChannelChannelIdEditRoute
  '/channel/$channelId/ideas': typeof ChannelChannelIdIdeasRoute
  '/channel/$channelId/narration': typeof ChannelChannelIdNarrationRoute
  '/channel/$channelId/publish': typeof ChannelChannelIdPublishRoute
  '/channel/$channelId/research': typeof ChannelChannelIdResearchRoute
  '/channel/$channelId/script': typeof ChannelChannelIdScriptRoute
  '/channel/$channelId/thumbnail': typeof ChannelChannelIdThumbnailRoute
  '/channel/$channelId/titles': typeof ChannelChannelIdTitlesRoute
  '/project/$projectId/assets': typeof ProjectProjectIdAssetsRoute
  '/project/$projectId/edit': typeof ProjectProjectIdEditRoute
  '/project/$projectId/ideas': typeof ProjectProjectIdIdeasRoute
  '/project/$projectId/narration': typeof ProjectProjectIdNarrationRoute
  '/project/$projectId/publish': typeof ProjectProjectIdPublishRoute
  '/project/$projectId/research': typeof ProjectProjectIdResearchRoute
  '/project/$projectId/script': typeof ProjectProjectIdScriptRoute
  '/project/$projectId/thumbnail': typeof ProjectProjectIdThumbnailRoute
  '/project/$projectId/titles': typeof ProjectProjectIdTitlesRoute
  '/channel/$channelId/': typeof ChannelChannelIdIndexRoute
  '/project/$projectId/': typeof ProjectProjectIdIndexRoute
  '/channel/$channelId/settings/processes': typeof ChannelChannelIdSettingsProcessesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/channel/$channelId/assets': typeof ChannelChannelIdAssetsRoute
  '/channel/$channelId/edit': typeof ChannelChannelIdEditRoute
  '/channel/$channelId/ideas': typeof ChannelChannelIdIdeasRoute
  '/channel/$channelId/narration': typeof ChannelChannelIdNarrationRoute
  '/channel/$channelId/publish': typeof ChannelChannelIdPublishRoute
  '/channel/$channelId/research': typeof ChannelChannelIdResearchRoute
  '/channel/$channelId/script': typeof ChannelChannelIdScriptRoute
  '/channel/$channelId/thumbnail': typeof ChannelChannelIdThumbnailRoute
  '/channel/$channelId/titles': typeof ChannelChannelIdTitlesRoute
  '/project/$projectId/assets': typeof ProjectProjectIdAssetsRoute
  '/project/$projectId/edit': typeof ProjectProjectIdEditRoute
  '/project/$projectId/ideas': typeof ProjectProjectIdIdeasRoute
  '/project/$projectId/narration': typeof ProjectProjectIdNarrationRoute
  '/project/$projectId/publish': typeof ProjectProjectIdPublishRoute
  '/project/$projectId/research': typeof ProjectProjectIdResearchRoute
  '/project/$projectId/script': typeof ProjectProjectIdScriptRoute
  '/project/$projectId/thumbnail': typeof ProjectProjectIdThumbnailRoute
  '/project/$projectId/titles': typeof ProjectProjectIdTitlesRoute
  '/channel/$channelId': typeof ChannelChannelIdIndexRoute
  '/project/$projectId': typeof ProjectProjectIdIndexRoute
  '/channel/$channelId/settings/processes': typeof ChannelChannelIdSettingsProcessesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/channel/$channelId/assets': typeof ChannelChannelIdAssetsRoute
  '/channel/$channelId/edit': typeof ChannelChannelIdEditRoute
  '/channel/$channelId/ideas': typeof ChannelChannelIdIdeasRoute
  '/channel/$channelId/narration': typeof ChannelChannelIdNarrationRoute
  '/channel/$channelId/publish': typeof ChannelChannelIdPublishRoute
  '/channel/$channelId/research': typeof ChannelChannelIdResearchRoute
  '/channel/$channelId/script': typeof ChannelChannelIdScriptRoute
  '/channel/$channelId/thumbnail': typeof ChannelChannelIdThumbnailRoute
  '/channel/$channelId/titles': typeof ChannelChannelIdTitlesRoute
  '/project/$projectId/assets': typeof ProjectProjectIdAssetsRoute
  '/project/$projectId/edit': typeof ProjectProjectIdEditRoute
  '/project/$projectId/ideas': typeof ProjectProjectIdIdeasRoute
  '/project/$projectId/narration': typeof ProjectProjectIdNarrationRoute
  '/project/$projectId/publish': typeof ProjectProjectIdPublishRoute
  '/project/$projectId/research': typeof ProjectProjectIdResearchRoute
  '/project/$projectId/script': typeof ProjectProjectIdScriptRoute
  '/project/$projectId/thumbnail': typeof ProjectProjectIdThumbnailRoute
  '/project/$projectId/titles': typeof ProjectProjectIdTitlesRoute
  '/channel/$channelId/': typeof ChannelChannelIdIndexRoute
  '/project/$projectId/': typeof ProjectProjectIdIndexRoute
  '/channel/$channelId/settings/processes': typeof ChannelChannelIdSettingsProcessesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/channel/$channelId/assets'
    | '/channel/$channelId/edit'
    | '/channel/$channelId/ideas'
    | '/channel/$channelId/narration'
    | '/channel/$channelId/publish'
    | '/channel/$channelId/research'
    | '/channel/$channelId/script'
    | '/channel/$channelId/thumbnail'
    | '/channel/$channelId/titles'
    | '/project/$projectId/assets'
    | '/project/$projectId/edit'
    | '/project/$projectId/ideas'
    | '/project/$projectId/narration'
    | '/project/$projectId/publish'
    | '/project/$projectId/research'
    | '/project/$projectId/script'
    | '/project/$projectId/thumbnail'
    | '/project/$projectId/titles'
    | '/channel/$channelId/'
    | '/project/$projectId/'
    | '/channel/$channelId/settings/processes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/channel/$channelId/assets'
    | '/channel/$channelId/edit'
    | '/channel/$channelId/ideas'
    | '/channel/$channelId/narration'
    | '/channel/$channelId/publish'
    | '/channel/$channelId/research'
    | '/channel/$channelId/script'
    | '/channel/$channelId/thumbnail'
    | '/channel/$channelId/titles'
    | '/project/$projectId/assets'
    | '/project/$projectId/edit'
    | '/project/$projectId/ideas'
    | '/project/$projectId/narration'
    | '/project/$projectId/publish'
    | '/project/$projectId/research'
    | '/project/$projectId/script'
    | '/project/$projectId/thumbnail'
    | '/project/$projectId/titles'
    | '/channel/$channelId'
    | '/project/$projectId'
    | '/channel/$channelId/settings/processes'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/channel/$channelId/assets'
    | '/channel/$channelId/edit'
    | '/channel/$channelId/ideas'
    | '/channel/$channelId/narration'
    | '/channel/$channelId/publish'
    | '/channel/$channelId/research'
    | '/channel/$channelId/script'
    | '/channel/$channelId/thumbnail'
    | '/channel/$channelId/titles'
    | '/project/$projectId/assets'
    | '/project/$projectId/edit'
    | '/project/$projectId/ideas'
    | '/project/$projectId/narration'
    | '/project/$projectId/publish'
    | '/project/$projectId/research'
    | '/project/$projectId/script'
    | '/project/$projectId/thumbnail'
    | '/project/$projectId/titles'
    | '/channel/$channelId/'
    | '/project/$projectId/'
    | '/channel/$channelId/settings/processes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ChannelChannelIdAssetsRoute: typeof ChannelChannelIdAssetsRoute
  ChannelChannelIdEditRoute: typeof ChannelChannelIdEditRoute
  ChannelChannelIdIdeasRoute: typeof ChannelChannelIdIdeasRoute
  ChannelChannelIdNarrationRoute: typeof ChannelChannelIdNarrationRoute
  ChannelChannelIdPublishRoute: typeof ChannelChannelIdPublishRoute
  ChannelChannelIdResearchRoute: typeof ChannelChannelIdResearchRoute
  ChannelChannelIdScriptRoute: typeof ChannelChannelIdScriptRoute
  ChannelChannelIdThumbnailRoute: typeof ChannelChannelIdThumbnailRoute
  ChannelChannelIdTitlesRoute: typeof ChannelChannelIdTitlesRoute
  ProjectProjectIdAssetsRoute: typeof ProjectProjectIdAssetsRoute
  ProjectProjectIdEditRoute: typeof ProjectProjectIdEditRoute
  ProjectProjectIdIdeasRoute: typeof ProjectProjectIdIdeasRoute
  ProjectProjectIdNarrationRoute: typeof ProjectProjectIdNarrationRoute
  ProjectProjectIdPublishRoute: typeof ProjectProjectIdPublishRoute
  ProjectProjectIdResearchRoute: typeof ProjectProjectIdResearchRoute
  ProjectProjectIdScriptRoute: typeof ProjectProjectIdScriptRoute
  ProjectProjectIdThumbnailRoute: typeof ProjectProjectIdThumbnailRoute
  ProjectProjectIdTitlesRoute: typeof ProjectProjectIdTitlesRoute
  ChannelChannelIdIndexRoute: typeof ChannelChannelIdIndexRoute
  ProjectProjectIdIndexRoute: typeof ProjectProjectIdIndexRoute
  ChannelChannelIdSettingsProcessesRoute: typeof ChannelChannelIdSettingsProcessesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId/': {
      id: '/project/$projectId/'
      path: '/project/$projectId'
      fullPath: '/project/$projectId/'
      preLoaderRoute: typeof ProjectProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel/$channelId/': {
      id: '/channel/$channelId/'
      path: '/channel/$channelId'
      fullPath: '/channel/$channelId/'
      preLoaderRoute: typeof ChannelChannelIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId/titles': {
      id: '/project/$projectId/titles'
      path: '/project/$projectId/titles'
      fullPath: '/project/$projectId/titles'
      preLoaderRoute: typeof ProjectProjectIdTitlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId/thumbnail': {
      id: '/project/$projectId/thumbnail'
      path: '/project/$projectId/thumbnail'
      fullPath: '/project/$projectId/thumbnail'
      preLoaderRoute: typeof ProjectProjectIdThumbnailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId/script': {
      id: '/project/$projectId/script'
      path: '/project/$projectId/script'
      fullPath: '/project/$projectId/script'
      preLoaderRoute: typeof ProjectProjectIdScriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId/research': {
      id: '/project/$projectId/research'
      path: '/project/$projectId/research'
      fullPath: '/project/$projectId/research'
      preLoaderRoute: typeof ProjectProjectIdResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId/publish': {
      id: '/project/$projectId/publish'
      path: '/project/$projectId/publish'
      fullPath: '/project/$projectId/publish'
      preLoaderRoute: typeof ProjectProjectIdPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId/narration': {
      id: '/project/$projectId/narration'
      path: '/project/$projectId/narration'
      fullPath: '/project/$projectId/narration'
      preLoaderRoute: typeof ProjectProjectIdNarrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId/ideas': {
      id: '/project/$projectId/ideas'
      path: '/project/$projectId/ideas'
      fullPath: '/project/$projectId/ideas'
      preLoaderRoute: typeof ProjectProjectIdIdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId/edit': {
      id: '/project/$projectId/edit'
      path: '/project/$projectId/edit'
      fullPath: '/project/$projectId/edit'
      preLoaderRoute: typeof ProjectProjectIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId/assets': {
      id: '/project/$projectId/assets'
      path: '/project/$projectId/assets'
      fullPath: '/project/$projectId/assets'
      preLoaderRoute: typeof ProjectProjectIdAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel/$channelId/titles': {
      id: '/channel/$channelId/titles'
      path: '/channel/$channelId/titles'
      fullPath: '/channel/$channelId/titles'
      preLoaderRoute: typeof ChannelChannelIdTitlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel/$channelId/thumbnail': {
      id: '/channel/$channelId/thumbnail'
      path: '/channel/$channelId/thumbnail'
      fullPath: '/channel/$channelId/thumbnail'
      preLoaderRoute: typeof ChannelChannelIdThumbnailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel/$channelId/script': {
      id: '/channel/$channelId/script'
      path: '/channel/$channelId/script'
      fullPath: '/channel/$channelId/script'
      preLoaderRoute: typeof ChannelChannelIdScriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel/$channelId/research': {
      id: '/channel/$channelId/research'
      path: '/channel/$channelId/research'
      fullPath: '/channel/$channelId/research'
      preLoaderRoute: typeof ChannelChannelIdResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel/$channelId/publish': {
      id: '/channel/$channelId/publish'
      path: '/channel/$channelId/publish'
      fullPath: '/channel/$channelId/publish'
      preLoaderRoute: typeof ChannelChannelIdPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel/$channelId/narration': {
      id: '/channel/$channelId/narration'
      path: '/channel/$channelId/narration'
      fullPath: '/channel/$channelId/narration'
      preLoaderRoute: typeof ChannelChannelIdNarrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel/$channelId/ideas': {
      id: '/channel/$channelId/ideas'
      path: '/channel/$channelId/ideas'
      fullPath: '/channel/$channelId/ideas'
      preLoaderRoute: typeof ChannelChannelIdIdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel/$channelId/edit': {
      id: '/channel/$channelId/edit'
      path: '/channel/$channelId/edit'
      fullPath: '/channel/$channelId/edit'
      preLoaderRoute: typeof ChannelChannelIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel/$channelId/assets': {
      id: '/channel/$channelId/assets'
      path: '/channel/$channelId/assets'
      fullPath: '/channel/$channelId/assets'
      preLoaderRoute: typeof ChannelChannelIdAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel/$channelId/settings/processes': {
      id: '/channel/$channelId/settings/processes'
      path: '/channel/$channelId/settings/processes'
      fullPath: '/channel/$channelId/settings/processes'
      preLoaderRoute: typeof ChannelChannelIdSettingsProcessesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ChannelChannelIdAssetsRoute: ChannelChannelIdAssetsRoute,
  ChannelChannelIdEditRoute: ChannelChannelIdEditRoute,
  ChannelChannelIdIdeasRoute: ChannelChannelIdIdeasRoute,
  ChannelChannelIdNarrationRoute: ChannelChannelIdNarrationRoute,
  ChannelChannelIdPublishRoute: ChannelChannelIdPublishRoute,
  ChannelChannelIdResearchRoute: ChannelChannelIdResearchRoute,
  ChannelChannelIdScriptRoute: ChannelChannelIdScriptRoute,
  ChannelChannelIdThumbnailRoute: ChannelChannelIdThumbnailRoute,
  ChannelChannelIdTitlesRoute: ChannelChannelIdTitlesRoute,
  ProjectProjectIdAssetsRoute: ProjectProjectIdAssetsRoute,
  ProjectProjectIdEditRoute: ProjectProjectIdEditRoute,
  ProjectProjectIdIdeasRoute: ProjectProjectIdIdeasRoute,
  ProjectProjectIdNarrationRoute: ProjectProjectIdNarrationRoute,
  ProjectProjectIdPublishRoute: ProjectProjectIdPublishRoute,
  ProjectProjectIdResearchRoute: ProjectProjectIdResearchRoute,
  ProjectProjectIdScriptRoute: ProjectProjectIdScriptRoute,
  ProjectProjectIdThumbnailRoute: ProjectProjectIdThumbnailRoute,
  ProjectProjectIdTitlesRoute: ProjectProjectIdTitlesRoute,
  ChannelChannelIdIndexRoute: ChannelChannelIdIndexRoute,
  ProjectProjectIdIndexRoute: ProjectProjectIdIndexRoute,
  ChannelChannelIdSettingsProcessesRoute:
    ChannelChannelIdSettingsProcessesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
